# Generated by using Rcpp::compileAttributes() -> do not edit by hand

chol_inv <- function(x) {
    .Call('_DNC_chol_inv', PACKAGE = 'DNC', x)
}

log_post_fun <- function(params, x, y, mu, sigma) {
    .Call('_DNC_log_post_fun', PACKAGE = 'DNC', params, x, y, mu, sigma)
}

log_post_fun_dnc <- function(params, x, y, mu, sigma, ratio) {
    .Call('_DNC_log_post_fun_dnc', PACKAGE = 'DNC', params, x, y, mu, sigma, ratio)
}

